/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MoisPaiementEnLigneService } from "../moisPaiementEnLigne.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MoisPaiementEnLigneCreateInput } from "./MoisPaiementEnLigneCreateInput";
import { MoisPaiementEnLigne } from "./MoisPaiementEnLigne";
import { MoisPaiementEnLigneFindManyArgs } from "./MoisPaiementEnLigneFindManyArgs";
import { MoisPaiementEnLigneWhereUniqueInput } from "./MoisPaiementEnLigneWhereUniqueInput";
import { MoisPaiementEnLigneUpdateInput } from "./MoisPaiementEnLigneUpdateInput";
import { OperationFindManyArgs } from "../../operation/base/OperationFindManyArgs";
import { Operation } from "../../operation/base/Operation";
import { OperationWhereUniqueInput } from "../../operation/base/OperationWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MoisPaiementEnLigneControllerBase {
  constructor(
    protected readonly service: MoisPaiementEnLigneService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: MoisPaiementEnLigne })
  @nestAccessControl.UseRoles({
    resource: "MoisPaiementEnLigne",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createMoisPaiementEnLigne(
    @common.Body() data: MoisPaiementEnLigneCreateInput
  ): Promise<MoisPaiementEnLigne> {
    return await this.service.createMoisPaiementEnLigne({
      data: {
        ...data,

        utilisateur: data.utilisateur
          ? {
              connect: data.utilisateur,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        mois: true,
        montantTotal: true,
        updatedAt: true,

        utilisateur: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [MoisPaiementEnLigne] })
  @ApiNestedQuery(MoisPaiementEnLigneFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "MoisPaiementEnLigne",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async moisPaiementEnLignes(
    @common.Req() request: Request
  ): Promise<MoisPaiementEnLigne[]> {
    const args = plainToClass(MoisPaiementEnLigneFindManyArgs, request.query);
    return this.service.moisPaiementEnLignes({
      ...args,
      select: {
        createdAt: true,
        id: true,
        mois: true,
        montantTotal: true,
        updatedAt: true,

        utilisateur: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: MoisPaiementEnLigne })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MoisPaiementEnLigne",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async moisPaiementEnLigne(
    @common.Param() params: MoisPaiementEnLigneWhereUniqueInput
  ): Promise<MoisPaiementEnLigne | null> {
    const result = await this.service.moisPaiementEnLigne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        mois: true,
        montantTotal: true,
        updatedAt: true,

        utilisateur: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: MoisPaiementEnLigne })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MoisPaiementEnLigne",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateMoisPaiementEnLigne(
    @common.Param() params: MoisPaiementEnLigneWhereUniqueInput,
    @common.Body() data: MoisPaiementEnLigneUpdateInput
  ): Promise<MoisPaiementEnLigne | null> {
    try {
      return await this.service.updateMoisPaiementEnLigne({
        where: params,
        data: {
          ...data,

          utilisateur: data.utilisateur
            ? {
                connect: data.utilisateur,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          mois: true,
          montantTotal: true,
          updatedAt: true,

          utilisateur: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: MoisPaiementEnLigne })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MoisPaiementEnLigne",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMoisPaiementEnLigne(
    @common.Param() params: MoisPaiementEnLigneWhereUniqueInput
  ): Promise<MoisPaiementEnLigne | null> {
    try {
      return await this.service.deleteMoisPaiementEnLigne({
        where: params,
        select: {
          createdAt: true,
          id: true,
          mois: true,
          montantTotal: true,
          updatedAt: true,

          utilisateur: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/operations")
  @ApiNestedQuery(OperationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Operation",
    action: "read",
    possession: "any",
  })
  async findOperations(
    @common.Req() request: Request,
    @common.Param() params: MoisPaiementEnLigneWhereUniqueInput
  ): Promise<Operation[]> {
    const query = plainToClass(OperationFindManyArgs, request.query);
    const results = await this.service.findOperations(params.id, {
      ...query,
      select: {
        categorie: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        date: true,
        id: true,

        moisPaiementEnLigne: {
          select: {
            id: true,
          },
        },

        montant: true,
        typeField: true,
        updatedAt: true,

        utilisateur: {
          select: {
            id: true,
          },
        },

        voyage: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/operations")
  @nestAccessControl.UseRoles({
    resource: "MoisPaiementEnLigne",
    action: "update",
    possession: "any",
  })
  async connectOperations(
    @common.Param() params: MoisPaiementEnLigneWhereUniqueInput,
    @common.Body() body: OperationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      operations: {
        connect: body,
      },
    };
    await this.service.updateMoisPaiementEnLigne({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/operations")
  @nestAccessControl.UseRoles({
    resource: "MoisPaiementEnLigne",
    action: "update",
    possession: "any",
  })
  async updateOperations(
    @common.Param() params: MoisPaiementEnLigneWhereUniqueInput,
    @common.Body() body: OperationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      operations: {
        set: body,
      },
    };
    await this.service.updateMoisPaiementEnLigne({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/operations")
  @nestAccessControl.UseRoles({
    resource: "MoisPaiementEnLigne",
    action: "update",
    possession: "any",
  })
  async disconnectOperations(
    @common.Param() params: MoisPaiementEnLigneWhereUniqueInput,
    @common.Body() body: OperationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      operations: {
        disconnect: body,
      },
    };
    await this.service.updateMoisPaiementEnLigne({
      where: params,
      data,
      select: { id: true },
    });
  }
}
