/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { VoyageService } from "../voyage.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { VoyageCreateInput } from "./VoyageCreateInput";
import { Voyage } from "./Voyage";
import { VoyageFindManyArgs } from "./VoyageFindManyArgs";
import { VoyageWhereUniqueInput } from "./VoyageWhereUniqueInput";
import { VoyageUpdateInput } from "./VoyageUpdateInput";
import { OperationFindManyArgs } from "../../operation/base/OperationFindManyArgs";
import { Operation } from "../../operation/base/Operation";
import { OperationWhereUniqueInput } from "../../operation/base/OperationWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class VoyageControllerBase {
  constructor(
    protected readonly service: VoyageService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Voyage })
  @nestAccessControl.UseRoles({
    resource: "Voyage",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createVoyage(@common.Body() data: VoyageCreateInput): Promise<Voyage> {
    return await this.service.createVoyage({
      data: {
        ...data,

        utilisateur: data.utilisateur
          ? {
              connect: data.utilisateur,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        dateDepart: true,
        dateRetour: true,
        id: true,
        updatedAt: true,

        utilisateur: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Voyage] })
  @ApiNestedQuery(VoyageFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Voyage",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async voyages(@common.Req() request: Request): Promise<Voyage[]> {
    const args = plainToClass(VoyageFindManyArgs, request.query);
    return this.service.voyages({
      ...args,
      select: {
        createdAt: true,
        dateDepart: true,
        dateRetour: true,
        id: true,
        updatedAt: true,

        utilisateur: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Voyage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Voyage",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async voyage(
    @common.Param() params: VoyageWhereUniqueInput
  ): Promise<Voyage | null> {
    const result = await this.service.voyage({
      where: params,
      select: {
        createdAt: true,
        dateDepart: true,
        dateRetour: true,
        id: true,
        updatedAt: true,

        utilisateur: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Voyage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Voyage",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateVoyage(
    @common.Param() params: VoyageWhereUniqueInput,
    @common.Body() data: VoyageUpdateInput
  ): Promise<Voyage | null> {
    try {
      return await this.service.updateVoyage({
        where: params,
        data: {
          ...data,

          utilisateur: data.utilisateur
            ? {
                connect: data.utilisateur,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          dateDepart: true,
          dateRetour: true,
          id: true,
          updatedAt: true,

          utilisateur: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Voyage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Voyage",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteVoyage(
    @common.Param() params: VoyageWhereUniqueInput
  ): Promise<Voyage | null> {
    try {
      return await this.service.deleteVoyage({
        where: params,
        select: {
          createdAt: true,
          dateDepart: true,
          dateRetour: true,
          id: true,
          updatedAt: true,

          utilisateur: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/operations")
  @ApiNestedQuery(OperationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Operation",
    action: "read",
    possession: "any",
  })
  async findOperations(
    @common.Req() request: Request,
    @common.Param() params: VoyageWhereUniqueInput
  ): Promise<Operation[]> {
    const query = plainToClass(OperationFindManyArgs, request.query);
    const results = await this.service.findOperations(params.id, {
      ...query,
      select: {
        categorie: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        date: true,
        id: true,

        moisPaiementEnLigne: {
          select: {
            id: true,
          },
        },

        montant: true,
        typeField: true,
        updatedAt: true,

        utilisateur: {
          select: {
            id: true,
          },
        },

        voyage: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/operations")
  @nestAccessControl.UseRoles({
    resource: "Voyage",
    action: "update",
    possession: "any",
  })
  async connectOperations(
    @common.Param() params: VoyageWhereUniqueInput,
    @common.Body() body: OperationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      operations: {
        connect: body,
      },
    };
    await this.service.updateVoyage({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/operations")
  @nestAccessControl.UseRoles({
    resource: "Voyage",
    action: "update",
    possession: "any",
  })
  async updateOperations(
    @common.Param() params: VoyageWhereUniqueInput,
    @common.Body() body: OperationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      operations: {
        set: body,
      },
    };
    await this.service.updateVoyage({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/operations")
  @nestAccessControl.UseRoles({
    resource: "Voyage",
    action: "update",
    possession: "any",
  })
  async disconnectOperations(
    @common.Param() params: VoyageWhereUniqueInput,
    @common.Body() body: OperationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      operations: {
        disconnect: body,
      },
    };
    await this.service.updateVoyage({
      where: params,
      data,
      select: { id: true },
    });
  }
}
