import { UserCategory } from "modules/users/enum";
import { authorizations } from "../enum";
import { User } from "modules/users";
import { isEmpty } from "lodash";

type Profile = 'client' | 'admin' | 'notCustomer';

export const getUserProfile = (user: User): Profile | null => {
    if (isEmpty(user)) return 'notCustomer';
    if (user?.category === UserCategory.DEFAULT) return 'client';
    if ((user?.category || 0) >= 500 && (user?.category || 0) <= 700) return 'admin';
    return null

}

export const getAuthorizationsByProfile = (profile: Profile): any => {
    //authorizations by functionalities
    // let adminActions: any[] = [];
    // const actions: { [key: string]: string[] } = {
    //     frontUsers: [
    //         'FRONT_USERS_FILTER_STATUS', 'FRONT_USERS_ADD_USER', 'FRONT_USERS_LIST_DETAIL', 'FRONT_USERS_EDIT',
    //         'FRONT_USERS_BTN_FILTER', 'FRONT_USERS_BTN_RESET'
    //     ],
    //     backUsers: [
    //         'BACK_USERS_FILTER_USERCODE', 'BACK_USERS_FILTER_CATEGORY', 'FILTER_BY_STATUS', 'BACK_USERS_EXPORT',
    //         'BACK_USERS_LIST_DETAIL', 'BACK_USERS_EDITION', 'BACK_USERS_BTN_FILTER', 'BACK_USERS_BTN_RESET', 'BACK_USERS_ADD_USER', 'BACK_USERS_FILTER_STATUS'
    //     ],
    //     travels: [
    //         'PROOF_TRAVEL_IMPORT', 'PROOF_TRAVEL_DECLARATION',
    //         'PROOF_TRAVEL_EDIT', 'UPLOAD_JUSTIFICATIONS', 'SAVE_EDITION', 'BTN_VALIDATE',
    //         'OPERATION_LIST_EXPORT', 'NOTIFS_LIST_EXPORT', 'VALIDATIONS_LIST_EXPORT'
    //     ],
    //     shortTravel: [
    //         'SHORT_TRAVEL_FILTER_NAME', 'SHORT_TRAVEL_FILTER_CLIENTCODE', 'SHORT_TRAVEL_FILTER_STATUS', 'SHORT_TRAVEL_FILTER_AGE',
    //         'SHORT_TRAVEL_FILTER_DATES', 'SHORT_TRAVEL_EXPORT', 'SHORT_TRAVEL_PROOF_TRAVEL', 'SHORT_TRAVEL_LIST_DETAIL', 'SHORT_TRAVEL_EDITION_MODE',
    //         'SHORT_TRAVEL_JUSTIFICATIONS', 'SHORT_TRAVEL_OPERATIONS_LIST', 'SHORT_TRAVEL_NOTIFICATIONS_LIST', 'SHORT_TRAVEL_VALIDATIONS_HISTORY',
    //         'SHORT_TRAVEL_EDITOR_HISTORY', 'SHORT_TRAVEL_EXPORT_FOLDER', 'SHORT_TRAVEL_BTN_FILTER', 'SHORT_TRAVEL_BTN_RESET', 'SHORT_TRAVEL_OTHER_BTN'
    //     ],
    //     longTravel: [
    //         'LONG_TRAVEL_FILTER_NAME', 'LONG_TRAVEL_FILTER_CLIENTCODE', 'LONG_TRAVEL_FILTER_STATUS', 'LONG_TRAVEL_FILTER_AGE',
    //         'LONG_TRAVEL_FILTER_DATES', 'LONG_TRAVEL_EXPORT', 'LONG_TRAVEL_PROOF_TRAVEL', 'LONG_TRAVEL_LIST_DETAIL', 'LONG_TRAVEL_JUSTIFICATIONS',
    //         'LONG_TRAVEL_MONTH_ECCEED_LIST', 'LONG_TRAVEL_NOTIFICATIONS_LIST', 'LONG_TRAVEL_VALIDATIONS_HISTORY', 'LONG_TRAVEL_EDITOR_HISTORY',
    //         'LONG_TRAVEL_BTN_FILTER', 'LONG_TRAVEL_BTN_RESET', 'LONG_TRAVEL_OTHER_BTN', 'LONG_TRAVEL_EDITION_MODE'
    //     ],
    //     onlinePayments: [
    //         'ONLINE_PAYMENT_DECLARATION', 'ONLINE_PAYMENT_IMPORT', 'ONLINE_PAYMENT_OTHER_BTN', 'ONLINE_PAYMENT_OPERATIONS_EXPORT',
    //         'ONLINE_PAYMENT_BTN_RESET', 'ONLINE_PAYMENT_BTN_FILTER', 'ONLINE_PAYMENT_FILTER_NAME', 'ONLINE_PAYMENT_FILTER_CLIENTCODE',
    //         'ONLINE_PAYMENT_FILTER_STATUS', 'ONLINE_PAYMENT_FILTER_AGE', 'ONLINE_PAYMENT_FILTER_DATES', 'ONLINE_PAYMENT_EXPORT', 'ONLINE_PAYMENT_LIST_DETAIL',
    //         'ONLINE_PAYMENT_EXPORT', 'ONLINE_PAYMENT_NEW_DECLARATION', 'ONLINE_PAYMENT_JUSTIFICATIONS', 'ONLINE_PAYMENT_OPERATIONS_LIST', 'ONLINE_PAYMENT_NOTIFICATIONS_LIST',
    //         'ONLINE_PAYMENT_VALIDATIONS_HISTORY', 'ONLINE_PAYMENT_EDITIONS_HISTORY', 'ONLINE_PAYMENT_VALIDATE', 'ONLINE_PAYMENT_EDITION_MODE'
    //     ],
    //     ceillingIncrease: [
    //         'CEILLING_LIST_DETAIL', 'CEILLING_FILTER_DATES', 'CEILLING_FILTER_CLIENTCODE', 'CEILLING_FILTER_ACCOUNT', 'CEILLING_FILTER_NAME',
    //         'CEILLING_BTN_FILTER', 'CEILLING_IN_PROGRESS', 'CEILLING_VALIDATE', 'CEILLING_REJECT', 'CEILLING_REQUEST', 'CEILLING_OTHERS_BTN', 'CEILLING_EDITION'
    //     ],
    //     importations: [
    //         'IMPORTATIONS_LIST_DETAIL', 'IMPORTATIONS_BTN_RESET', 'IMPORTATIONS_BTN_FILTER', 'IMPORTATIONS_EDITION', 'IMPORTATIONS_FILTER_TYPE',
    //         'IMPORTATIONS_FILTER_CLIENTCODE', 'IMPORTATIONS_FILTER_STATUS', 'IMPORTATIONS_FILTER_AGE', 'IMPORTATIONS_FILTER_DATES'
    //     ],
    //     reporting: [
    //         'REPORT_CONSOLIDATE', 'REPORT_AVERAGE_TIME', 'REPORT_STATUS_OPERATIONS', 'REPORT_LINE_CHART', 'REPORT_BTN_RESET', 'REPORT_BTN_FILTER',
    //         'REPORT_FILTER_DATES', 'REPORT_FILTER_TYPE', 'REPORT_FILTER_AGE', 'REPORT_FILTER_REGION',
    //     ],
    //     fileImport: [
    //         'FILE_IMPORT_LIST_DETAIL', 'FILE_IMPORT_FILTER_NAME', 'FILE_IMPORT_BTN_RESET', 'FILE_IMPORT_BTN_FILTER', 'FILE_IMPORT_EXPORT',
    //         'FILE_IMPORT_IMPORT', 'FILE_IMPORT_EXPORT'
    //     ],
    //     formalNotice: [
    //         'FORMAL_NOTICE_FILTER_DATES', 'FORMAL_NOTICE_FILTER_TYPE', 'FORMAL_NOTICE_FILTER_STATUS', 'FORMAL_NOTICE_BTN_FILTER',
    //         'FORMAL_NOTICE_EXPORT', 'FORMAL_NOTICE_LIST_DETAIL'
    //     ],
    //     instantNotif: [
    //         'FIND_INSTANT_NOTIF'
    //     ],
    //     notificationlist: [
    //         'NOTIF_FILTER_DATES', 'NOTIF_FILTER_TYPE', 'NOTIF_FILTER_STATUS', 'NOTIF_BTN_FILTER',
    //         'NOTIF_EXPORT', 'NOTIF_WHATSAP_DETAIL', 'NOTIF_SMS_DETAIL', 'NOTIF_MAIL_DETAIL'
    //     ],
    //     generalsSetting: [
    //         'GENERAL_SETTING_LIST_DETAIL', 'GENERAL_SETTING_BTN_RESET', 'GENERAL_SETTING_BTN_FILTER', 'GENERAL_SETTING_FILTER_NAME', 'GENERAL_SETTING_EDITION'
    //     ],
    //     vouchersSetting: [
    //         'VOUCHERS_SETTING_LIST_DETAIL', 'VOUCHERS_SETTING_BTN_NEW', 'VOUCHERS_SETTING_EDITON'
    //     ],
    //     templateSetting: [
    //         'TEMPLATE_SETTING_BTN_RESET', 'TEMPLATE_SETTING_FILTER_NAME', 'TEMPLATE_SETTING_VARIABLES_LIST',
    //         'TEMPLATE_SETTING_LIST_DETAIL', 'TEMPLATE_SETTING_EDITION', 'TEMPLATE_SETTING_ENABLE_BTN'
    //     ],
    //     formalNoticeSetting: [
    //         'FORMAL_NOTICE_SETTING_VARIABLES_LIS', 'FORMAL_NOTICE_SETTING_PREVIEW', 'FORMAL_NOTICE_SETTING_IMPORT', 'FORMAL_NOTICE_SETTING_EDITION'
    //     ],
    //     cartTypeSetting: [
    //         'CART_SETTING_LIST_DETAIL', 'CART_SETTING_BTN_NEW', 'CART_SETTING_EDITION', 'CART_SETTING_ENABLE_BTN'
    //     ],
    //     longTravelTypeSetting: [
    //         'TRAVEL_TYPE_SETTING_LIST_DETAIL', 'TRAVEL_TYPE_SETTING_EDITION', 'TRAVEL_TYPE_SETTING_BTN_NEW'
    //     ],
    //     onlinePaymentTypeSetting: [
    //         'ONLINE_PAYMENT_TYPE_SETTING_EXPORT', 'ONLINE_PAYMENT_TYPE_SETTING_BTN_NEW', 'ONLINE_PAYMENT_TYPE_SETTING_LIST_DETAIL', 'ONLINE_PAYMENT_TYPE_SETTING_EDITION'
    //     ],
    //     ceillingSetting: [
    //         'CEILLING_SETTING_LIST_DETAIL', 'CEILLING_SETTING_EDITION'
    //     ],
    //     validationLevelSetting: [
    //         'VALIDATION_LEVEL_SETTING_BTN_NEW', 'VALIDATION_LEVEL_SETTING_LIST_DETAIL', 'VALIDATION_LEVEL_SETTING_EDITION'
    //     ],
    //     transactionTypeSetting: [
    //         'TRANS_TYPE_SETTING_LIST_DETAIL', 'TRANS_TYPE_SETTING_BTN_NEW', 'TRANS_TYPE_SETTING_EDITION', 'TRANS_TYPE_SETTING_BTN_DELETE'
    //     ],
    //     share: [
    //         'SIGN_BUTTON', 'SIDE-BAR'
    //     ]
    // }
    // for (const key in actions) { adminActions = [...adminActions, ...actions[key]] }
    const admin = Object.entries(authorizations).map(([key]) => { return key; });

    const _authorizations = {
        admin,
        client: [
            'DECLARATIONS', 'NEW_DECLARATION', 'FILTER_BY_STATUS', 'TRAVEL_RECAP', 'OPERATIONS_LIST', 'JUSTIFICATIONS',
            'PROOF_TRAVEL_EDIT', 'UPLOAD_JUSTIFICATIONS', 'SAVE_EDITION', 'MONTH_RECAP', 'MONTH_ECCEED_LIST',
            'NEW_CEILLING_INCREASE', 'GET_USER_ID', 'SHOW_EXCEED_DAYS', 'SIGN_BUTTON', 'SIDE_BAR'
        ],
        notCustomer: [
            'FILTER_BY_STATUS', 'TRAVEL_RECAP', 'OPERATIONS_LIST', 'JUSTIFICATIONS', 'PROOF_TRAVEL_EDIT', 'UPLOAD_JUSTIFICATIONS',
            'SAVE_EDITION', 'MONTH_RECAP', 'MONTH_ECCEED_LIST', 'NEW_CEILLING_INCREASE'
        ],
    };

    return _authorizations[profile]
}















