/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Operation } from "./Operation";
import { OperationCountArgs } from "./OperationCountArgs";
import { OperationFindManyArgs } from "./OperationFindManyArgs";
import { OperationFindUniqueArgs } from "./OperationFindUniqueArgs";
import { CreateOperationArgs } from "./CreateOperationArgs";
import { UpdateOperationArgs } from "./UpdateOperationArgs";
import { DeleteOperationArgs } from "./DeleteOperationArgs";
import { Categorie } from "../../categorie/base/Categorie";
import { MoisPaiementEnLigne } from "../../moisPaiementEnLigne/base/MoisPaiementEnLigne";
import { Utilisateur } from "../../utilisateur/base/Utilisateur";
import { Voyage } from "../../voyage/base/Voyage";
import { OperationService } from "../operation.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Operation)
export class OperationResolverBase {
  constructor(
    protected readonly service: OperationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Operation",
    action: "read",
    possession: "any",
  })
  async _operationsMeta(
    @graphql.Args() args: OperationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Operation])
  @nestAccessControl.UseRoles({
    resource: "Operation",
    action: "read",
    possession: "any",
  })
  async operations(
    @graphql.Args() args: OperationFindManyArgs
  ): Promise<Operation[]> {
    return this.service.operations(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Operation, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Operation",
    action: "read",
    possession: "own",
  })
  async operation(
    @graphql.Args() args: OperationFindUniqueArgs
  ): Promise<Operation | null> {
    const result = await this.service.operation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Operation)
  @nestAccessControl.UseRoles({
    resource: "Operation",
    action: "create",
    possession: "any",
  })
  async createOperation(
    @graphql.Args() args: CreateOperationArgs
  ): Promise<Operation> {
    return await this.service.createOperation({
      ...args,
      data: {
        ...args.data,

        categorie: args.data.categorie
          ? {
              connect: args.data.categorie,
            }
          : undefined,

        moisPaiementEnLigne: args.data.moisPaiementEnLigne
          ? {
              connect: args.data.moisPaiementEnLigne,
            }
          : undefined,

        utilisateur: args.data.utilisateur
          ? {
              connect: args.data.utilisateur,
            }
          : undefined,

        voyage: args.data.voyage
          ? {
              connect: args.data.voyage,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Operation)
  @nestAccessControl.UseRoles({
    resource: "Operation",
    action: "update",
    possession: "any",
  })
  async updateOperation(
    @graphql.Args() args: UpdateOperationArgs
  ): Promise<Operation | null> {
    try {
      return await this.service.updateOperation({
        ...args,
        data: {
          ...args.data,

          categorie: args.data.categorie
            ? {
                connect: args.data.categorie,
              }
            : undefined,

          moisPaiementEnLigne: args.data.moisPaiementEnLigne
            ? {
                connect: args.data.moisPaiementEnLigne,
              }
            : undefined,

          utilisateur: args.data.utilisateur
            ? {
                connect: args.data.utilisateur,
              }
            : undefined,

          voyage: args.data.voyage
            ? {
                connect: args.data.voyage,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Operation)
  @nestAccessControl.UseRoles({
    resource: "Operation",
    action: "delete",
    possession: "any",
  })
  async deleteOperation(
    @graphql.Args() args: DeleteOperationArgs
  ): Promise<Operation | null> {
    try {
      return await this.service.deleteOperation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Categorie, {
    nullable: true,
    name: "categorie",
  })
  @nestAccessControl.UseRoles({
    resource: "Categorie",
    action: "read",
    possession: "any",
  })
  async getCategorie(
    @graphql.Parent() parent: Operation
  ): Promise<Categorie | null> {
    const result = await this.service.getCategorie(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => MoisPaiementEnLigne, {
    nullable: true,
    name: "moisPaiementEnLigne",
  })
  @nestAccessControl.UseRoles({
    resource: "MoisPaiementEnLigne",
    action: "read",
    possession: "any",
  })
  async getMoisPaiementEnLigne(
    @graphql.Parent() parent: Operation
  ): Promise<MoisPaiementEnLigne | null> {
    const result = await this.service.getMoisPaiementEnLigne(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Utilisateur, {
    nullable: true,
    name: "utilisateur",
  })
  @nestAccessControl.UseRoles({
    resource: "Utilisateur",
    action: "read",
    possession: "any",
  })
  async getUtilisateur(
    @graphql.Parent() parent: Operation
  ): Promise<Utilisateur | null> {
    const result = await this.service.getUtilisateur(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Voyage, {
    nullable: true,
    name: "voyage",
  })
  @nestAccessControl.UseRoles({
    resource: "Voyage",
    action: "read",
    possession: "any",
  })
  async getVoyage(@graphql.Parent() parent: Operation): Promise<Voyage | null> {
    const result = await this.service.getVoyage(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
