/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Operation as PrismaOperation,
  Categorie as PrismaCategorie,
  MoisPaiementEnLigne as PrismaMoisPaiementEnLigne,
  Utilisateur as PrismaUtilisateur,
  Voyage as PrismaVoyage,
} from "@prisma/client";

export class OperationServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.OperationCountArgs, "select">
  ): Promise<number> {
    return this.prisma.operation.count(args);
  }

  async operations(
    args: Prisma.OperationFindManyArgs
  ): Promise<PrismaOperation[]> {
    return this.prisma.operation.findMany(args);
  }
  async operation(
    args: Prisma.OperationFindUniqueArgs
  ): Promise<PrismaOperation | null> {
    return this.prisma.operation.findUnique(args);
  }
  async createOperation(
    args: Prisma.OperationCreateArgs
  ): Promise<PrismaOperation> {
    return this.prisma.operation.create(args);
  }
  async updateOperation(
    args: Prisma.OperationUpdateArgs
  ): Promise<PrismaOperation> {
    return this.prisma.operation.update(args);
  }
  async deleteOperation(
    args: Prisma.OperationDeleteArgs
  ): Promise<PrismaOperation> {
    return this.prisma.operation.delete(args);
  }

  async getCategorie(parentId: string): Promise<PrismaCategorie | null> {
    return this.prisma.operation
      .findUnique({
        where: { id: parentId },
      })
      .categorie();
  }

  async getMoisPaiementEnLigne(
    parentId: string
  ): Promise<PrismaMoisPaiementEnLigne | null> {
    return this.prisma.operation
      .findUnique({
        where: { id: parentId },
      })
      .moisPaiementEnLigne();
  }

  async getUtilisateur(parentId: string): Promise<PrismaUtilisateur | null> {
    return this.prisma.operation
      .findUnique({
        where: { id: parentId },
      })
      .utilisateur();
  }

  async getVoyage(parentId: string): Promise<PrismaVoyage | null> {
    return this.prisma.operation
      .findUnique({
        where: { id: parentId },
      })
      .voyage();
  }
}
