/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PieceJointeService } from "../pieceJointe.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PieceJointeCreateInput } from "./PieceJointeCreateInput";
import { PieceJointe } from "./PieceJointe";
import { PieceJointeFindManyArgs } from "./PieceJointeFindManyArgs";
import { PieceJointeWhereUniqueInput } from "./PieceJointeWhereUniqueInput";
import { PieceJointeUpdateInput } from "./PieceJointeUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PieceJointeControllerBase {
  constructor(
    protected readonly service: PieceJointeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PieceJointe })
  @nestAccessControl.UseRoles({
    resource: "PieceJointe",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPieceJointe(
    @common.Body() data: PieceJointeCreateInput
  ): Promise<PieceJointe> {
    return await this.service.createPieceJointe({
      data: {
        ...data,

        categorie: data.categorie
          ? {
              connect: data.categorie,
            }
          : undefined,

        typePieceJointe: data.typePieceJointe
          ? {
              connect: data.typePieceJointe,
            }
          : undefined,
      },
      select: {
        categorie: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        nomFichier: true,

        typePieceJointe: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        url: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PieceJointe] })
  @ApiNestedQuery(PieceJointeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PieceJointe",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async pieceJointes(@common.Req() request: Request): Promise<PieceJointe[]> {
    const args = plainToClass(PieceJointeFindManyArgs, request.query);
    return this.service.pieceJointes({
      ...args,
      select: {
        categorie: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        nomFichier: true,

        typePieceJointe: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        url: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PieceJointe })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PieceJointe",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async pieceJointe(
    @common.Param() params: PieceJointeWhereUniqueInput
  ): Promise<PieceJointe | null> {
    const result = await this.service.pieceJointe({
      where: params,
      select: {
        categorie: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        nomFichier: true,

        typePieceJointe: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        url: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PieceJointe })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PieceJointe",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePieceJointe(
    @common.Param() params: PieceJointeWhereUniqueInput,
    @common.Body() data: PieceJointeUpdateInput
  ): Promise<PieceJointe | null> {
    try {
      return await this.service.updatePieceJointe({
        where: params,
        data: {
          ...data,

          categorie: data.categorie
            ? {
                connect: data.categorie,
              }
            : undefined,

          typePieceJointe: data.typePieceJointe
            ? {
                connect: data.typePieceJointe,
              }
            : undefined,
        },
        select: {
          categorie: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          nomFichier: true,

          typePieceJointe: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PieceJointe })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PieceJointe",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePieceJointe(
    @common.Param() params: PieceJointeWhereUniqueInput
  ): Promise<PieceJointe | null> {
    try {
      return await this.service.deletePieceJointe({
        where: params,
        select: {
          categorie: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          nomFichier: true,

          typePieceJointe: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
