import {
    FrontUsersAuthorizationsRead, FrontUsersAuthorizationsWrite, BackUsersAuthorizationsRead, BackUsersAuthorizationsWrite, TravelsDeclarationAuthorizationsRead,
    TravelsAuthorizationsWrite, ShortTravelAuthorizationsRead, ShortTravelAuthorizationsWrite, LongTravelAuthorizationsRead, LongTravelAuthorizationsWrite,
    OnlinePaymentsAuthorizationsRead, OnlinePaymentsAuthorizationsWrite, CeilingIncreaseAuthorizationsRead, CeilingIncreaseAuthorizationsWrite, ImportationsAuthorizationsRead,
    GeneralsSettingAuthorizationsWrite, VouchersSettingAuthorizationsRead, VouchersSettingAuthorizationsWrite, TemplateSettingAuthorizationsRead, TemplateSettingAuthorizationsWrite,
    InstantNotificationAuthorizationsRead, InstantNotificationAuthorizationsWrite, NotificationListAuthorizationsRead, NotificationListAuthorizationsWrite, GeneralsSettingAuthorizationsRead,
    ImportationsAuthorizationsWrite, ReportingAuthorizationsRead, FileImportAuthorizationsRead, FileImportAuthorizationsWrite, FormalNoticeAuthorizationsRead, FormalNoticeAuthorizationsWrite,
    FormalNoticeSettingAuthorizationsRead, FormalNoticeSettingAuthorizationsWrite, CartTypeSettingAuthorizationsRead, CartTypeSettingAuthorizationsWrite, LongTravelTypeSettingAuthorizationsRead,
    ValidationLevelSettingAuthorizationsRead, ValidationLevelSettingAuthorizationsWrite, TransactionTypeSettingAuthorizationsRead, TransactionTypeSettingAuthorizationsWrite, ShareAuthorizationsRead,
    LongTravelTypeSettingAuthorizationsWrite, OnlinePaymentTypeSettingAuthorizationsRead, OnlinePaymentTypeSettingAuthorizationsWrite, CeilingSettingAuthorizationsRead, CeilingSettingAuthorizationsWrite,
    DCHAuthorizationsRead, DCHAuthorizationsWrite, HeadOfPersonnelAgencyPermissionRead, HeadOfPersonnelAgencyPermissionWrite, HeadOfRegionPermissionRead, HeadOfRegionPermissionWrite, ManagementCommitteeAuthorizationsRead,
    ManagementCommitteeAuthorizationsWrite, PersonnelManagerPermissionRead, PersonnelManagerPermissionWrite, TravelsMenuAuthorizationsRead, OnlinePaymentsMenuAuthorizationsRead, OnlinePaymentsDeclarationAuthorizationsRead,
    SettingsMenuAuthorizationsRead, UsersMenuAuthorizationsRead, OperationsAuthorizationsRead, OperationsMenuAuthorizationsRead, OperationsAuthorizationsWrite, TransferStakeholdersMenuAuthorizationsRead, TransferStakeholdersAuthorizationsRead,
    TransferStakeholdersAuthorizationsWrite, SensitiveNotificationListMenuAuthorizationsRead, SensitiveNotificationListAuthorizationsWrite, SensitiveNotificationListAuthorizationsRead,
} from "../../enum";

const _superAdmin = {
    ...UsersMenuAuthorizationsRead,
    ...FrontUsersAuthorizationsRead,
    ...FrontUsersAuthorizationsWrite,
    ...BackUsersAuthorizationsRead,
    ...BackUsersAuthorizationsWrite,
    ...TravelsMenuAuthorizationsRead,
    ...TravelsDeclarationAuthorizationsRead,
    ...TravelsAuthorizationsWrite,
    ...ShortTravelAuthorizationsRead,
    ...ShortTravelAuthorizationsWrite,
    ...LongTravelAuthorizationsRead,
    ...LongTravelAuthorizationsWrite,
    ...OnlinePaymentsMenuAuthorizationsRead,
    ...OnlinePaymentsDeclarationAuthorizationsRead,
    ...OnlinePaymentsAuthorizationsRead,
    ...OnlinePaymentsAuthorizationsWrite,
    ...CeilingIncreaseAuthorizationsRead,
    ...CeilingIncreaseAuthorizationsWrite,
    ...ImportationsAuthorizationsRead,
    ...ImportationsAuthorizationsWrite,
    ...ReportingAuthorizationsRead,
    ...InstantNotificationAuthorizationsRead,
    ...InstantNotificationAuthorizationsWrite,
    ...NotificationListAuthorizationsRead,
    ...NotificationListAuthorizationsWrite,
    ...SensitiveNotificationListMenuAuthorizationsRead,
    ...SensitiveNotificationListAuthorizationsRead,
    ...SensitiveNotificationListAuthorizationsWrite,
    ...FormalNoticeAuthorizationsRead,
    ...FormalNoticeAuthorizationsWrite,
    ...SettingsMenuAuthorizationsRead,
    ...GeneralsSettingAuthorizationsRead,
    ...GeneralsSettingAuthorizationsWrite,
    ...FileImportAuthorizationsRead,
    ...FileImportAuthorizationsWrite,
    ...VouchersSettingAuthorizationsRead,
    ...VouchersSettingAuthorizationsWrite,
    ...TemplateSettingAuthorizationsRead,
    ...TemplateSettingAuthorizationsWrite,
    ...FormalNoticeSettingAuthorizationsRead,
    ...FormalNoticeSettingAuthorizationsWrite,
    ...CartTypeSettingAuthorizationsRead,
    ...CartTypeSettingAuthorizationsWrite,
    ...LongTravelTypeSettingAuthorizationsRead,
    ...LongTravelTypeSettingAuthorizationsWrite,
    ...OnlinePaymentTypeSettingAuthorizationsRead,
    ...OnlinePaymentTypeSettingAuthorizationsWrite,
    ...CeilingSettingAuthorizationsRead,
    ...CeilingSettingAuthorizationsWrite,
    ...ValidationLevelSettingAuthorizationsRead,
    ...ValidationLevelSettingAuthorizationsWrite,
    ...TransactionTypeSettingAuthorizationsRead,
    ...TransactionTypeSettingAuthorizationsWrite,
    ...ShareAuthorizationsRead,
    ...DCHAuthorizationsRead,
    ...DCHAuthorizationsWrite,
    ...ManagementCommitteeAuthorizationsRead,
    ...ManagementCommitteeAuthorizationsWrite,
    ...HeadOfRegionPermissionRead,
    ...HeadOfRegionPermissionWrite,
    ...HeadOfPersonnelAgencyPermissionRead,
    ...HeadOfPersonnelAgencyPermissionWrite,
    ...PersonnelManagerPermissionRead,
    ...PersonnelManagerPermissionWrite,
    ...OperationsMenuAuthorizationsRead,
    ...OperationsAuthorizationsRead,
    ...OperationsAuthorizationsWrite,
    ...TransferStakeholdersMenuAuthorizationsRead,
    ...TransferStakeholdersAuthorizationsRead,
    ...TransferStakeholdersAuthorizationsWrite,
};

// Object.entries(_superAdmin).forEach(([k, v]: any) => {
//     (/^[A-Z_-]+$/.test(k)) && (_superAdmin[k] = k);
//     (/^[A-Z_-]+$/.test(`${v}`)) && (delete _superAdmin[k]);
// });

export const superAdmin = _superAdmin;

export const authorizations = superAdmin;
// export const authorizations = Object.entries(superAdmin).map(([key]) => { return key; });

export type Authorizations = keyof typeof _superAdmin;
