// authorizations by functionalities

export enum FrontUsersAuthorizations {
    FRONT_USERS_FILTER_STATUS, FRONT_USERS_ADD_USER, FRONT_USERS_LIST_DETAIL, FRONT_USERS_EDIT,
    FRONT_USERS_BTN_FILTER, FRONT_USERS_BTN_RESET
}

export enum BackUsersAuthorizations {
    BACK_USERS_FILTER_USER_CODE, BACK_USERS_FILTER_CATEGORY, FILTER_BY_STATUS, BACK_USERS_EXPORT, BACK_USERS_CREATE,
    BACK_USERS_LIST_DETAIL, BACK_USERS_EDITION, BACK_USERS_BTN_FILTER, BACK_USERS_BTN_RESET, BACK_USERS_ADD_USER, BACK_USERS_FILTER_STATUS
}
export enum TravelsAuthorizations {
    PROOF_TRAVEL_IMPORT, PROOF_TRAVEL_DECLARATION,
    PROOF_TRAVEL_EDIT, UPLOAD_JUSTIFICATIONS, SAVE_EDITION, BTN_VALIDATE,
    OPERATION_LIST_EXPORT, NOTIFICATIONS_LIST_EXPORT, VALIDATIONS_LIST_EXPORT
}
export enum ShortTravelAuthorizations {
    SHORT_TRAVEL_FILTER_NAME, SHORT_TRAVEL_FILTER_CLIENT_CODE, SHORT_TRAVEL_FILTER_STATUS, SHORT_TRAVEL_FILTER_AGE,
    SHORT_TRAVEL_FILTER_DATES, SHORT_TRAVEL_EXPORT, SHORT_TRAVEL_PROOF_TRAVEL, SHORT_TRAVEL_LIST_DETAIL, SHORT_TRAVEL_EDITION_MODE,
    SHORT_TRAVEL_JUSTIFICATIONS, SHORT_TRAVEL_OPERATIONS_LIST, SHORT_TRAVEL_NOTIFICATIONS_LIST, SHORT_TRAVEL_VALIDATIONS_HISTORY,
    SHORT_TRAVEL_EDITOR_HISTORY, SHORT_TRAVEL_EXPORT_FOLDER, SHORT_TRAVEL_BTN_FILTER, SHORT_TRAVEL_BTN_RESET, SHORT_TRAVEL_OTHER_BTN
}
export enum LongTravelAuthorizations {
    LONG_TRAVEL_FILTER_NAME, LONG_TRAVEL_FILTER_CLIENT_CODE, LONG_TRAVEL_FILTER_STATUS, LONG_TRAVEL_FILTER_AGE,
    LONG_TRAVEL_FILTER_DATES, LONG_TRAVEL_EXPORT, LONG_TRAVEL_PROOF_TRAVEL, LONG_TRAVEL_LIST_DETAIL, LONG_TRAVEL_JUSTIFICATIONS,
    LONG_TRAVEL_MONTH_EXCEED_LIST, LONG_TRAVEL_NOTIFICATIONS_LIST, LONG_TRAVEL_VALIDATIONS_HISTORY, LONG_TRAVEL_EDITOR_HISTORY,
    LONG_TRAVEL_BTN_FILTER, LONG_TRAVEL_BTN_RESET, LONG_TRAVEL_OTHER_BTN, LONG_TRAVEL_EDITION_MODE
}
export enum OnlinePaymentsAuthorizations {
    ONLINE_PAYMENT_DECLARATION, ONLINE_PAYMENT_IMPORT, ONLINE_PAYMENT_OTHER_BTN, ONLINE_PAYMENT_OPERATIONS_EXPORT,
    ONLINE_PAYMENT_BTN_RESET, ONLINE_PAYMENT_BTN_FILTER, ONLINE_PAYMENT_FILTER_NAME, ONLINE_PAYMENT_FILTER_CLIENT_CODE,
    ONLINE_PAYMENT_FILTER_STATUS, ONLINE_PAYMENT_FILTER_AGE, ONLINE_PAYMENT_FILTER_DATES, ONLINE_PAYMENT_EXPORT, ONLINE_PAYMENT_LIST_DETAIL,
    ONLINE_PAYMENT_NEW_DECLARATION, ONLINE_PAYMENT_JUSTIFICATIONS, ONLINE_PAYMENT_OPERATIONS_LIST, ONLINE_PAYMENT_NOTIFICATIONS_LIST,
    ONLINE_PAYMENT_VALIDATIONS_HISTORY, ONLINE_PAYMENT_EDITIONS_HISTORY, ONLINE_PAYMENT_VALIDATE, ONLINE_PAYMENT_EDITION_MODE
}
export enum CeilingIncreaseAuthorizations {
    CEILING_LIST_DETAIL, CEILING_FILTER_DATES, CEILING_FILTER_CLIENT_CODE, CEILING_FILTER_ACCOUNT, CEILING_FILTER_NAME,
    CEILING_BTN_FILTER, CEILING_IN_PROGRESS, CEILING_VALIDATE, CEILING_REJECT, CEILING_REQUEST, CEILING_OTHERS_BTN, CEILING_EDITION
}
export enum ImportationsAuthorizations {
    IMPORTATIONS_LIST_DETAIL, IMPORTATIONS_BTN_RESET, IMPORTATIONS_BTN_FILTER, IMPORTATIONS_EDITION, IMPORTATIONS_FILTER_TYPE,
    IMPORTATIONS_FILTER_CLIENT_CODE, IMPORTATIONS_FILTER_STATUS, IMPORTATIONS_FILTER_AGE, IMPORTATIONS_FILTER_DATES
}
export enum ReportingAuthorizations {
    REPORT_CONSOLIDATE, REPORT_AVERAGE_TIME, REPORT_STATUS_OPERATIONS, REPORT_LINE_CHART, REPORT_BTN_RESET, REPORT_BTN_FILTER,
    REPORT_FILTER_DATES, REPORT_FILTER_TYPE, REPORT_FILTER_AGE, REPORT_FILTER_REGION,
}
export enum FileImportAuthorizations {
    FILE_IMPORT_LIST_DETAIL, FILE_IMPORT_FILTER_NAME, FILE_IMPORT_BTN_RESET, FILE_IMPORT_BTN_FILTER, FILE_IMPORT_EXPORT,
    FILE_IMPORT_IMPORT
}
export enum FormalNoticeAuthorizations {
    FORMAL_NOTICE_FILTER_DATES, FORMAL_NOTICE_FILTER_TYPE, FORMAL_NOTICE_FILTER_STATUS, FORMAL_NOTICE_BTN_FILTER,
    FORMAL_NOTICE_EXPORT, FORMAL_NOTICE_LIST_DETAIL
}
export enum InstantNotificationAuthorizations {
    FIND_INSTANT_NOTIFICATION
}
export enum NotificationListAuthorizations {
    NOTIFICATION_FILTER_DATES, NOTIFICATION_FILTER_TYPE, NOTIFICATION_FILTER_STATUS, NOTIFICATION_BTN_FILTER,
    NOTIFICATION_EXPORT, NOTIFICATION_WHATSAPP_DETAIL, NOTIFICATION_SMS_DETAIL, NOTIFICATION_MAIL_DETAIL
}
export enum GeneralsSettingAuthorizations {
    GENERAL_SETTING_LIST_DETAIL, GENERAL_SETTING_BTN_RESET, GENERAL_SETTING_BTN_FILTER, GENERAL_SETTING_FILTER_NAME, GENERAL_SETTING_EDITION
}
export enum VouchersSettingAuthorizations {
    VOUCHERS_SETTING_LIST_DETAIL, VOUCHERS_SETTING_BTN_NEW, VOUCHERS_SETTING_EDITION
}
export enum TemplateSettingAuthorizations {
    TEMPLATE_SETTING_BTN_RESET, TEMPLATE_SETTING_FILTER_NAME, TEMPLATE_SETTING_VARIABLES_LIST,
    TEMPLATE_SETTING_LIST_DETAIL, TEMPLATE_SETTING_EDITION, TEMPLATE_SETTING_ENABLE_BTN
}
export enum FormalNoticeSettingAuthorizations {
    FORMAL_NOTICE_SETTING_VARIABLES_LIST, FORMAL_NOTICE_SETTING_PREVIEW, FORMAL_NOTICE_SETTING_IMPORT, FORMAL_NOTICE_SETTING_EDITION
}
export enum CartTypeSettingAuthorizations {
    CART_SETTING_LIST_DETAIL, CART_SETTING_BTN_NEW, CART_SETTING_EDITION, CART_SETTING_ENABLE_BTN
}
export enum LongTravelTypeSettingAuthorizations {
    TRAVEL_TYPE_SETTING_LIST_DETAIL, TRAVEL_TYPE_SETTING_EDITION, TRAVEL_TYPE_SETTING_BTN_NEW
}
export enum OnlinePaymentTypeSettingAuthorizations {
    ONLINE_PAYMENT_TYPE_SETTING_EXPORT, ONLINE_PAYMENT_TYPE_SETTING_BTN_NEW, ONLINE_PAYMENT_TYPE_SETTING_LIST_DETAIL, ONLINE_PAYMENT_TYPE_SETTING_EDITION
}
export enum CeilingSettingAuthorizations {
    CEILING_SETTING_LIST_DETAIL, CEILING_SETTING_EDITION
}
export enum ValidationLevelSettingAuthorizations {
    VALIDATION_LEVEL_SETTING_BTN_NEW, VALIDATION_LEVEL_SETTING_LIST_DETAIL, VALIDATION_LEVEL_SETTING_EDITION
}
export enum TransactionTypeSettingAuthorizations {
    TRANS_TYPE_SETTING_LIST_DETAIL, TRANS_TYPE_SETTING_BTN_NEW, TRANS_TYPE_SETTING_EDITION, TRANS_TYPE_SETTING_BTN_DELETE
}
export enum ShareAuthorizations {
    SIGN_BUTTON, SIDE_BAR
}

const _authorizations = {
    ...FrontUsersAuthorizations,
    ...BackUsersAuthorizations,
    ...TravelsAuthorizations,
    ...ShortTravelAuthorizations,
    ...LongTravelAuthorizations,
    ...OnlinePaymentsAuthorizations,
    ...CeilingIncreaseAuthorizations,
    ...ImportationsAuthorizations,
    ...ReportingAuthorizations,
    ...FileImportAuthorizations,
    ...FormalNoticeAuthorizations,
    ...InstantNotificationAuthorizations,
    ...NotificationListAuthorizations,
    ...GeneralsSettingAuthorizations,
    ...VouchersSettingAuthorizations,
    ...TemplateSettingAuthorizations,
    ...FormalNoticeSettingAuthorizations,
    ...CartTypeSettingAuthorizations,
    ...LongTravelTypeSettingAuthorizations,
    ...OnlinePaymentTypeSettingAuthorizations,
    ...CeilingSettingAuthorizations,
    ...ValidationLevelSettingAuthorizations,
    ...TransactionTypeSettingAuthorizations,
    ...ShareAuthorizations
};

Object.entries(_authorizations).forEach(([k, v]: any) => {
    (/^[A-Z_-]+$/.test(k)) && (_authorizations[k] = k);
    (/^[A-Z_-]+$/.test(`${v}`)) && (delete _authorizations[k]);
});

export const authorizations = _authorizations;

export type Authorizations = keyof typeof _authorizations;
