/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  ValidateNested,
  MaxLength,
} from "class-validator";
import { MoisPaiementEnLigneUpdateManyWithoutUtilisateursInput } from "./MoisPaiementEnLigneUpdateManyWithoutUtilisateursInput";
import { Type } from "class-transformer";
import { OperationUpdateManyWithoutUtilisateursInput } from "./OperationUpdateManyWithoutUtilisateursInput";
import { RoleWhereUniqueInput } from "../../role/base/RoleWhereUniqueInput";
import { VoyageUpdateManyWithoutUtilisateursInput } from "./VoyageUpdateManyWithoutUtilisateursInput";

@InputType()
class UtilisateurUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => MoisPaiementEnLigneUpdateManyWithoutUtilisateursInput,
  })
  @ValidateNested()
  @Type(() => MoisPaiementEnLigneUpdateManyWithoutUtilisateursInput)
  @IsOptional()
  @Field(() => MoisPaiementEnLigneUpdateManyWithoutUtilisateursInput, {
    nullable: true,
  })
  moisPaiementEnLignes?: MoisPaiementEnLigneUpdateManyWithoutUtilisateursInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  motDePasse?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nom?: string | null;

  @ApiProperty({
    required: false,
    type: () => OperationUpdateManyWithoutUtilisateursInput,
  })
  @ValidateNested()
  @Type(() => OperationUpdateManyWithoutUtilisateursInput)
  @IsOptional()
  @Field(() => OperationUpdateManyWithoutUtilisateursInput, {
    nullable: true,
  })
  operations?: OperationUpdateManyWithoutUtilisateursInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  prenom?: string | null;

  @ApiProperty({
    required: false,
    type: () => RoleWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => RoleWhereUniqueInput)
  @IsOptional()
  @Field(() => RoleWhereUniqueInput, {
    nullable: true,
  })
  role?: RoleWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => VoyageUpdateManyWithoutUtilisateursInput,
  })
  @ValidateNested()
  @Type(() => VoyageUpdateManyWithoutUtilisateursInput)
  @IsOptional()
  @Field(() => VoyageUpdateManyWithoutUtilisateursInput, {
    nullable: true,
  })
  voyages?: VoyageUpdateManyWithoutUtilisateursInput;
}

export { UtilisateurUpdateInput as UtilisateurUpdateInput };
